
#ifndef SHADERLIST_H
#define SHADERLIST_H
enum SHADER_TYPE
{
    INVALID_SHADER_TYPE = 0,
    PLAIN_COLOR_SHADER = 1,
    PLAIN_TEXTURE_SHADER = 2,
    PLAIN_SMOOTH_SHADER = 3,
    MULTITEXTURE_SMOOTH_SHADER = 4,
};
#endif // SHADERLIST_H
